definitions:
  dtos.Event:
    type: object
  dtos.Response:
    properties:
      data: {}
      domainErrorCode:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
  description: REST API server for Borealis aka 'the Feedback' app
  title: Borealis
  version: "2.0"
paths:
  /api/v1/events:
    get:
      consumes:
      - application/json
      description: Creates an event
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dtos.Response'
            - properties:
                data:
                  $ref: '#/definitions/dtos.Event'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dtos.Response'
        "419":
          description: ""
          schema:
            $ref: '#/definitions/dtos.Response'
      summary: Creates an event
      tags:
      - Event
swagger: "2.0"
